//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 12:38:16 PM IST 
//


package com.frontpaw.forecast.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Financials"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}EconTagTree"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "financials",
    "econTagTree"
})
@XmlRootElement(name = "EconMetrics")
public class EconMetrics {

    @XmlElement(name = "Financials", required = true)
    protected Financials financials;
    @XmlElement(name = "EconTagTree", required = true)
    protected EconTagTree econTagTree;
    /**
     * Gets the value of the financials property.
     * 
     * @return
     *     possible object is
     *     {@link Financials }
     *     
     */
    public Financials getFinancials() {
        return financials;
    }

    /**
     * Sets the value of the financials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Financials }
     *     
     */
    public void setFinancials(Financials value) {
        this.financials = value;
    }
    /**
     * Gets the value of the econTagTree property.
     * 
     * @return
     *     possible object is
     *     {@link EconTagTree }
     *     
     */
    public EconTagTree getEconTagTree() {
        return econTagTree;
    }

    /**
     * Sets the value of the econTagTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link EconTagTree }
     *     
     */
    public void setEconTagTree(EconTagTree value) {
        this.econTagTree = value;
    }


}
