//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.29 at 08:25:46 PM IST 
//


package com.frontpaw.forecast.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Name"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Value"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Measuree"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}EconTagNodes1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "value",
    "measuree",
    "econTagNodes"
})
@XmlRootElement(name = "EconTagNodes")
public class EconTagNodes {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Value", required = true)
    protected String value;
    @XmlElement(name = "Measure", required = true)
    protected List<Measuree> measuree;
    @XmlElement(name = "EconTagNode", required = true)
    protected List<EconTagNodes> econTagNodes;

    public void setMeasuree(List<Measuree> measuree) {
		this.measuree = measuree;
	}

	public List<Measuree> getMeasuree() {
		if (measuree == null) {
			measuree = new ArrayList<Measuree>();
       }
		return this.measuree;
	}

	/**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    public List<EconTagNodes> getEconTagNodes() {
		if (econTagNodes == null) {
			econTagNodes = new ArrayList<EconTagNodes>();
       }

		return this.econTagNodes;
	}

	public void setEconTagNodes(List<EconTagNodes> econTagNodes) {
		this.econTagNodes = econTagNodes;
	}

	/**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the measuree property.
     * 
     * @return
     *     possible object is
     *     {@link Measuree }
     *     
     */
    /*public Measuree getMeasuree() {
        return measuree;
    }

    /**
     * Sets the value of the measuree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measuree }
     *     
     *
    public void setMeasuree(Measuree value) {
        this.measuree = value;
    }*/

}
