//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 12:38:16 PM IST 
//


package com.frontpaw.forecast.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}ForecastID"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Description"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Status"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}RunTime"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}PeriodZero"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}PeriodCount"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}ReportFreq"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}EconomicUnit"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Log"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Periods"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Dates"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Models"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Metrics"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "forecastID",
    "description",
    "status",
    "runTime",
    "periodZero",
    "periodCount",
    "reportFreq",
    "economicUnit",
    "log",
    "periods",
    "dates",
    "models",
    "metrics"
})
@XmlRootElement(name = "Forecast")
public class Forecast {

    @XmlElement(name = "ForecastID", required = true)
    protected String forecastID;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "RunTime", required = true)
    protected String runTime;
    @XmlElement(name = "PeriodZero", required = true)
    protected String periodZero;
    @XmlElement(name = "PeriodCount", required = true)
    protected String periodCount;
    @XmlElement(name = "ReportFreq", required = true)
    protected String reportFreq;
    @XmlElement(name = "EconomicUnit", required = true)
    protected EconomicUnit economicUnit;
    @XmlElement(name = "Log", required = true)
    protected Log log;
    @XmlElement(name = "Periods", required = true)
    protected Periods periods;
    @XmlElement(name = "Dates", required = true)
    protected Dates dates;
    @XmlElement(name = "Models", required = true)
    protected Models models;
    @XmlElement(name = "Metrics", required = true)
    protected Metrics metrics;

    /**
     * Gets the value of the forecastID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForecastID() {
        return forecastID;
    }

    /**
     * Sets the value of the forecastID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForecastID(String value) {
        this.forecastID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunTime(String value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the periodZero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodZero() {
        return periodZero;
    }

    /**
     * Sets the value of the periodZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodZero(String value) {
        this.periodZero = value;
    }

    /**
     * Gets the value of the periodCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodCount() {
        return periodCount;
    }

    /**
     * Sets the value of the periodCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodCount(String value) {
        this.periodCount = value;
    }

    /**
     * Gets the value of the reportFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFreq() {
        return reportFreq;
    }

    /**
     * Sets the value of the reportFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFreq(String value) {
        this.reportFreq = value;
    }

    /**
     * Gets the value of the economicUnit property.
     * 
     * @return
     *     possible object is
     *     {@link EconomicUnit }
     *     
     */
    public EconomicUnit getEconomicUnit() {
        return economicUnit;
    }

    /**
     * Sets the value of the economicUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link EconomicUnit }
     *     
     */
    public void setEconomicUnit(EconomicUnit value) {
        this.economicUnit = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the periods property.
     * 
     * @return
     *     possible object is
     *     {@link Periods }
     *     
     */
    public Periods getPeriods() {
        return periods;
    }

    /**
     * Sets the value of the periods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periods }
     *     
     */
    public void setPeriods(Periods value) {
        this.periods = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link Dates }
     *     
     */
    public Dates getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dates }
     *     
     */
    public void setDates(Dates value) {
        this.dates = value;
    }

    /**
     * Gets the value of the models property.
     * 
     * @return
     *     possible object is
     *     {@link Models }
     *     
     */
    public Models getModels() {
        return models;
    }

    /**
     * Sets the value of the models property.
     * 
     * @param value
     *     allowed object is
     *     {@link Models }
     *     
     */
    public void setModels(Models value) {
        this.models = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link Metrics }
     *     
     */
    public Metrics getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metrics }
     *     
     */
    public void setMetrics(Metrics value) {
        this.metrics = value;
    }

}
