//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.29 at 08:25:46 PM IST 
//


package com.frontpaw.forecast.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Account"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Value"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}EbbName"/>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}EbbUserName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account",
    "value",
    "ebbName",
    "ebbUserName"
})
@XmlRootElement(name = "Measuree")
public class Measuree {

    @XmlElement(name = "Account", required = true)
    protected String account;
    @XmlElement(name = "Value", required = true)
    protected String value;
    @XmlElement(name = "EbbName", required = true)
    protected String ebbName;
    @XmlElement(name = "EbbUserName", required = true)
    protected String ebbUserName;

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccount(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the ebbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbbName() {
        return ebbName;
    }

    /**
     * Sets the value of the ebbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbbName(String value) {
        this.ebbName = value;
    }

    /**
     * Gets the value of the ebbUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEbbUserName() {
        return ebbUserName;
    }

    /**
     * Sets the value of the ebbUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEbbUserName(String value) {
        this.ebbUserName = value;
    }

}
