//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 12:38:16 PM IST 
//


package com.frontpaw.forecast.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://frontpaw.com/2002/10/generatedschema}Perpetual"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "perpetual",
    "oneTime"
})
@XmlRootElement(name = "StrategyTiming")
public class StrategyTiming {

    @XmlElement(name = "Perpetual", required = true)
    protected String perpetual;
    @XmlElement(name = "OneTime", required = true)
    protected OneTime oneTime;

    /**
     * Gets the value of the perpetual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerpetual() {
        return perpetual;
    }

    /**
     * Sets the value of the perpetual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerpetual(String value) {
        this.perpetual = value;
    }

    /**
     * Gets the value of the oneTime property.
     * 
     * @return
     *     possible object is
     *     {@link OneTime }
     *     
     */
    public OneTime getOneTime() {
        return oneTime;
    }

    /**
     * Sets the value of the oneTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneTime }
     *     
     */
    public void setOneTime(OneTime value) {
        this.oneTime = value;
    }
}
